version: '3.5'
services:
  app:
    container_name: express-app
    restart: always
    build: .
    image: ltoth/node-web-app
    environment:
      - VIRTUAL_PORT=3000
      - VIRTUAL_HOST=${URL}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    networks:
      - webproxy
networks:
  webproxy:
   name: webproxy